In [1]:
import numpy as np

In [2]:
x = np.arange(4)

In [5]:
 print(x // 2)

[0 0 1 1]


In [6]:
x = np.arange(1, 3)

In [8]:
np.multiply.reduce(x)

2

In [9]:
x = np.arange(1, 11) 

In [10]:
np.multiply.outer(x, x)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [11]:
a.	np.multiply(x, x).reshape(10,10)

NameError: name 'a' is not defined

In [12]:
b.	np.multiply(x, x)

NameError: name 'b' is not defined

In [14]:
np.multiply(x, x).shape(10,10)

TypeError: 'tuple' object is not callable

In [15]:
x = [1, 2, 3] 

In [16]:
np.power(1, x) 

array([1, 1, 1], dtype=int32)

In [17]:
np.power(x, 1) 

array([1, 2, 3], dtype=int32)

In [18]:
x = np.array([2, 1, 4, 3, 5]) 

In [19]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [20]:
x

array([2, 1, 4, 3, 5])