In [1]:
#Example: What Is the Average Height of US Presidents?
!notepad data/president_heights.csv

In [2]:
import pandas as pd
data = pd.read_csv('data/president_heights.csv')

In [3]:
import numpy as np

In [4]:
heights = np.array(data['height(cm)'])
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [5]:
print("Mean height:       ", heights.mean())
print("Standard Deviation:", heights.std())
print("Minimum height:    ", heights.min())
print("Maximum height:    ", heights.max())

Mean height:        179.73809523809524
Standard Deviation: 6.931843442745892
Minimum height:     163
Maximum height:     193


In [19]:
a = np.arange(3)

In [20]:
a

array([0, 1, 2])

In [21]:
a.shape

(3,)

In [22]:
a[:,np.newaxis].shape

(3, 1)

In [23]:
#Centering an array
X=np.random.random((10,3))
X

array([[0.82386846, 0.83162254, 0.18207395],
       [0.29951422, 0.4461364 , 0.09181341],
       [0.84625129, 0.75677292, 0.79347053],
       [0.39477494, 0.7009942 , 0.18025265],
       [0.21396624, 0.33031121, 0.04559652],
       [0.26698245, 0.13201678, 0.4197614 ],
       [0.8983655 , 0.55199051, 0.79003458],
       [0.88482745, 0.9767327 , 0.06124079],
       [0.04978382, 0.67706529, 0.01411036],
       [0.56820334, 0.42611028, 0.82234155]])

In [24]:
Xmean = X.mean(0)

In [25]:
Xmean

array([0.52465377, 0.58297528, 0.34006957])

In [29]:
Xmean = X.mean(1)
Xmean

array([0.61252165, 0.27915467, 0.79883158, 0.4253406 , 0.19662465,
       0.27292021, 0.74679686, 0.64093364, 0.24698649, 0.60555172])

In [30]:
x = np.linspace(0, 5, 50)

In [35]:
#Example: Counting Rainy Days
import numpy as np
import pandas as pd

# use Pandas to extract rainfall inches as a NumPy array
rainfall = pd.read_csv('data/Seattle2014.csv')['PRCP'].values
#print(rainfall)

inches = rainfall / 254 # 1/10mm -> inches
inches.shape


(365,)